services:
  db:
    image: postgres:17.0
    restart: always
    environment:
      - POSTGRES_USER=administrador
      - POSTGRES_PASSWORD=Pass123!
    ports:
      - 6000:5432

  webapi:
    image: jryoy/webapi
    restart: always
    environment:
      - ConnectionStrings__PostgresConnection=Server=db;Database=BD_WebApi;Username=administrador;Password=Pass123!
    ports:
      - 5000:5000
    depends_on:
      - db

